### ISSUE TITLE
InkWhale PSP tokens - Warning at ascan

### ISSUE THREAD

**Issue by SoA432** [SyncraDAO/psp-tokenlist#49]
Currently there are 3 tokens created by [InkWhale app](https://a0.inkwhale.net/#/create/token) which were verified via this repo and got warning at ascan. 
From public information - once tokens are created and minted via `InkWhale app` there no ways to mint more tokens. Correct me if i am wrong.
May it be just issue with `info.json` where we should drop owner, or this `owners` can interact directly with contract to mint new tokens? 
Probably this is issue more related to `InkWhale team`, since @DamianStraszak you already in contact with team, can you check please if everything is correct?

Example:
<img width="614" alt="Снимок экрана 2024-07-24 в 16 21 43" src="https://github.com/user-attachments/assets/9492ede1-894a-40c5-b94a-1deb0542321f">

References:
Warning - [SHIT](https://github.com/SyncraDAO/psp-tokenlist/tree/main/tokens/psp22/5F9aiiwLMPC6fFxxwqHvJpm7h5T4Xm93mJT6cpDrQnKkLFoK)
Warning - [IOU](https://github.com/SyncraDAO/psp-tokenlist/tree/main/tokens/psp22/5GCubYQbm9x6TQbthbWpUVrgEibXMDXhgisw8DFYCpPJQ5f7)
Warning - [KEBAB](https://github.com/SyncraDAO/psp-tokenlist/tree/main/tokens/psp22/5GVjxVdUMr5dQX9TSvvwWq42jyRaXLN65MDh4A8jhdG4Rz1A)

**Comment by DamianStraszak** [comment]
As you can see, for IOU (and similarly the rest) the submitted information mentions the existence of an owner who can mint new tokens (see the owner and minter field) https://github.com/SyncraDAO/psp-tokenlist/blob/main/tokens/psp22/5GCubYQbm9x6TQbthbWpUVrgEibXMDXhgisw8DFYCpPJQ5f7/info.json. This is also confirmed by querying the contract. 

So the warnings are correct. Once the ownership and minting rights are renounced on these tokens, the information can be updated here, so that ascan does not show warnings anymore.

**Comment by SoA432** [comment]
> existence

So to fix such warning - all meme token owners who used `InkWhale` to create tokens need to contact `Ink Whale` team, to renounce of ownership and minting rights since its not happens automatically and cant be setup via their UI ? Am i get everything correct @DamianStraszak ?

**Comment by DamianStraszak** [comment]
Yes, I think that would be advisable.

**Comment by SoA432** [comment]
For reference:

https://ui.use.ink/add-contract -> [Use On-Chain Contract Address](https://ui.use.ink/address-lookup) -> enter contract address -> use related function of your contract (for example renounceOwnership)
